XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXX
XXXX XXXXXXXX XXXX XXXX XXX
XXXXX XXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX

XXXX XXXXXXXX XXXXXX XXX XXXXXXXXX XXXXX XXX XXXXX XXX

BBBBBBB BBBBBBBBBBBBBBBBBB

XXXX XXXX XXXXXXXX XXX XXXXXXXXX XXXXXXX XX XXXX XX XXXXXX XXXXXXX

XX XXXXXX XXXXXXX
XX XXXXXXXXXXXXXXX					X XXXXX XXXXXX

XX XXXXX XXXXXXX
XX XXXXXXXXXXXXXXXXXX       X XXXXXXXXX XXXXX XXXXX XXXXXXX

XX XXXXXXX XXXXXXX
XX XXXXXXXXXXXXXXXX					X XXXXX XXXXXXX
XX XXXXXXXXXXXXXXXXX				X XXXXXX XXXXXXX
XX XXXXXXXXXXXXXXXXXXXXX		X XXX XXXXXX XXXXXXX
XX XXXXXXXXXXXXXXXXXXXX			X XXXXXXXXX XXXXXXX XXXXX XXXXXX
XX XXXXXXXXXXXXXXXXXX			  X XXXXXXX XXXXXXX

XX XXXXX XXXXXXX
XX XXXXXXXXXXXXXXXXXXX			X XXXXX XXXXX XXXX
XX XXXXXXXXXXXXXXXXXXXX			X XXXXXX XXXXX XXXX
XX XXXXXXXXXXXXXXXXXXXXXXXX	X XXX XXXXXX XXXXX XXXX

XX XXXXXXXXXX XXXXXXX
XX XXXXXXXXXXXXXXXXXXX			X XXXXX XXXXXXXXXX

XX XXXXXX XXXXXXX
XX XXXXXXXXXXXXXXX					X XXXXX XXXXXX

XXX

XXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBB

        XXXX XXXX XXXXXXX XXX
        XXXXX XXXXXXXXXXXXX

            XXXX XXXXXXXXXX XXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBB

            XXXX XXXX XXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                BBBBBBB BBBBBBBBBBBBBBBBBBBB 
                BBBBB BBBBBBB BBBBBBBB
                XXXXXXXX XXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXX XXX
        XXXXXXX


        XXXXXXXXX XXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBB


    XXXXXX

    XXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBB
    XXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBB
    XXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBB

XXXXXXX

XXXXXXX