BBBB BBBBBB
XXX XXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXBBB BBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX

    XXXX XXXXXXXXXX XXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
            XX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXX XXXXXXBBB BBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXX

    BBBBB BBBBBBBBBB
    BBBBBBBB
XXXXX