BBBB BBBBBB
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XXXX XXXXXX XXXXXXXXX XXXXX XXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX
    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBXX
    XXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXX XXXXX XXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX

    XXXX XXXX XXXXXX XXX XXXX XXXXXXXXXXX XXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX

    BBBBB BBBBBBBBB
    BBBBBBBB
XXXXXXX