BBBB BBBBBB
XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
    XXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXX
            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXX
    XXXXX

    XXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBB
        XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        BBBBB
        XXX XXXXXXXXXXXXXXX XXXXXXXXXX
            XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX

                XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX

                    XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBB
                XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBXX
                    XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXBBBBBXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX

                XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXX
                    XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXX XXXXXXXX
                    XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXX
    XXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX BBBBB BBBBBB BBBBBBBB

XXXXXXXXX