BBBB BBBBBB
XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XX
                XXX XXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXX

                XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXX
                XXXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
                        XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBXX
                        XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX

                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
                        XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX

                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
            XXXXX
        XXXXXX

        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX BBBBB BBBBBBB BBBBBBBB
    XXXXXX
XXXXXX