# Generated by Django 2.2.8 on 2020-02-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='cpf',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
