# Generated by Django 2.2.8 on 2020-02-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
