# Generated by Django 2.2.8 on 2019-12-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
