# Generated by Django 2.2.2 on 2020-02-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='sexo',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='Profile',
        ),
    ]
