# Generated by Django 2.2.2 on 2020-02-26 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0002_auto_20200226_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Perfil'},
        ),
    ]
