# Generated by Django 2.2.2 on 2020-02-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0003_auto_20200226_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profile'},
        ),
    ]
