# Generated by Django 2.2.8 on 2020-02-20 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0003_collaborator_next'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborator',
            old_name='next',
            new_name='nextToken',
        ),
    ]
