# Generated by Django 2.2.8 on 2020-02-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0004_auto_20200216_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='cpf',
            field=models.CharField(max_length=15, null=True, verbose_name='CPF'),
        ),
    ]
