# Generated by Django 2.2.8 on 2020-02-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0005_collaborator_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='cpf',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='phone number'),
        ),
    ]
