# Generated by Django 2.2.8 on 2020-02-16 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0006_auto_20200216_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='landline',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='sexo',
        ),
    ]
