# Generated by Django 2.2.8 on 2020-02-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0007_auto_20200216_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='cpf',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='landline',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='landline'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True),
        ),
    ]
