# Generated by Django 2.2.8 on 2020-02-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0016_auto_20200217_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='isWhatsapp',
            field=models.BooleanField(default=False, verbose_name='Is whatsapp'),
        ),
    ]
