BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBBBB
BBBBB BBB
XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

BBBBBBBB

XXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
XXXXXX
XXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                BBB BBBBBBB BB BBBBBBB
                XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXX XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
                             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX
                             XXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXX XXXX XXXX XXXX XXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXXXX
                        BBBB
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
                                XXX XXXXXX XXXXX XXX XXXX XXXXXXXXXXXXXXXXXXXXX
                        BBBBB

                        XXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXX XXX
                            BB BBBBBBBBBB
                            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
                            BBBB
                            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXXX
                            XXXXXXXXXXXX
                            BBBBB
                            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                            BB BBBBBBBBBBBBBB
                            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXX
                            XXXX
                                BBBB
                            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX
                            XXXX
                                BBBBB
                            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXX
                            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXX XXXXXXXXX
                                 FFFFFFFFFFFF
                            XXXXX
                            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXX XXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX X
                                XXXXXXXXXXXX XX
                            XXXXX
                            XXXXXXXX
                        XXXXX
                        XX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXX
                                XXXXXXXXXX XXXXXXXXXXXX
                                XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                BBBBBB
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX
BBBBBBBB