# Generated by Django 2.2.2 on 2020-03-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='type_appointment',
        ),
        migrations.AddField(
            model_name='appointment',
            name='type_appointment',
            field=models.ManyToManyField(to='appointment.TypeAppointment', verbose_name='Type appointment'),
        ),
    ]
