# Generated by Django 2.2.2 on 2020-03-11 23:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20200307_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date_appointment',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=14, verbose_name='date of appointment'),
            preserve_default=False,
        ),
    ]
