# Generated by Django 2.2.2 on 2020-03-14 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointment_date_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='collaborator.Profile', verbose_name='Professional'),
        ),
    ]
