# Generated by Django 2.2.2 on 2020-03-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20200314_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consulting',
            field=models.BooleanField(default=False, verbose_name='Consulting'),
        ),
    ]
