# Generated by Django 2.2.2 on 2020-03-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_appointment_consulting'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='isCanceled',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
