# Generated by Django 2.2.2 on 2020-03-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_appointment_iscanceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booked',
            field=models.BooleanField(null=True, verbose_name='Booked'),
        ),
    ]
