# Generated by Django 2.2.2 on 2020-03-22 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_appointment_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='booked',
        ),
    ]
