# Generated by Django 2.2.2 on 2020-03-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_remove_appointment_booked'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPacient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
