# Generated by Django 2.2.2 on 2020-03-22 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacient', '0030_auto_20200322_1640'),
        ('appointment', '0010_notificationpacient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationpacient',
            options={'verbose_name': 'Notification Support Team', 'verbose_name_plural': 'Notification Support Team'},
        ),
        migrations.AddField(
            model_name='notificationpacient',
            name='action',
            field=models.CharField(choices=[('appointment-saved', 'Notify to pacientes appointments')], default=1, max_length=200, verbose_name='Action'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationpacient',
            name='pacient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pacient.Pacient', verbose_name='Pacient'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='notificationpacient',
            table='NotificationSupportTeam',
        ),
    ]
