# Generated by Django 2.2.2 on 2020-03-22 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacient', '0032_auto_20200322_1649'),
        ('appointment', '0012_auto_20200322_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpacient',
            name='pacient',
        ),
        migrations.AddField(
            model_name='notificationpacient',
            name='pacient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pacient.Pacient', verbose_name='Pacient'),
            preserve_default=False,
        ),
    ]
