# Generated by Django 2.2.2 on 2020-03-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0014_auto_20200322_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeappointment',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
