# Generated by Django 2.2.2 on 2020-03-22 20:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0015_auto_20200322_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='calendarOwnerTID',
            field=models.IntegerField(default=553917231, editable=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='calendarUUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
