# Generated by Django 2.2.2 on 2020-03-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0016_auto_20200322_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(default=None, max_length=60, null=True, verbose_name='Appointment name'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='calendarOwnerTID',
            field=models.IntegerField(default=-193239630, editable=False),
        ),
    ]
