BBBB BBBBBB

BBBBB BBB
XXXXXXXXXX
BBBBBBB BBBBBBBBBBBBBBB
BBBBBBB BBBBBBBBBBBBBBBBBBBB

XXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXX XXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB
XXXXXXXXX
BBBBBBB BBBBBBBBBBBBBB

BBBBB BBBBBBB
XXXXX XXXXXXXXXXXXX XXXXXXXXXXX
    BBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    
                XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    
                XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    
                XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    
                XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXX XXXXXX X XX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X XXXXXX XX XXXXXXX XXXX XX XXXXXXXX XXXX
                        XXXXX XXXXXX XXX XXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    
                XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    
                XXXXXX
                XXXX
            XXXXXX
            
          
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            
                        XXXXXX
                    XXXXXX

                XXXXXX
                  
                XXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            
                        XXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX
                            
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
XXXXXXX

BBBBBBBB