BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBBB
XXXXX XXXXXXXXXXXXX XXXXXXXXXXX
    BBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    
                XXXXXX
                XXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXXXX
XXXXXXX
BBBBBBBB