# Generated by Django 2.2.2 on 2020-02-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('medical_record_number', models.IntegerField(default=0, verbose_name='Medical record number')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='photo')),
                ('rg_document', models.CharField(blank=True, max_length=14, null=True, verbose_name='rg document')),
                ('cpf_document', models.CharField(blank=True, max_length=14, null=True, verbose_name='cpf document')),
                ('date_of_birth', models.DateField(blank=True, max_length=14, null=True, verbose_name='Date of birth')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='phone number')),
                ('isWhatsapp', models.BooleanField(default=False, verbose_name='Is whatsapp')),
                ('landline', models.CharField(blank=True, max_length=15, null=True, verbose_name='landline')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=254, null=True, verbose_name='Address')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'pacient',
                'verbose_name_plural': 'pacient',
                'db_table': 'pacient',
            },
        ),
    ]
