# Generated by Django 2.2.2 on 2020-02-28 19:30

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pacient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacient',
            old_name='nome',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='pacient',
            name='photo',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Photo'),
        ),
    ]
