# Generated by Django 2.2.2 on 2020-02-28 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacient', '0002_auto_20200228_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacient',
            name='isWhatsapp',
        ),
    ]
