# Generated by Django 2.2.2 on 2020-02-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacient', '0005_auto_20200228_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='medical_record_number',
            field=models.IntegerField(blank=True, default=18070503, editable=False, null=True, verbose_name='Medical record number'),
        ),
    ]
