# Generated by Django 2.2.2 on 2020-02-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacient', '0007_auto_20200229_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='medical_record_number',
            field=models.IntegerField(blank=True, default=25051995, editable=False, null=True, verbose_name='Medical record number'),
        ),
    ]
