# Generated by Django 2.2.2 on 2020-02-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacient', '0008_auto_20200229_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='medical_record_number',
            field=models.IntegerField(blank=True, default=25052007, editable=False, null=True, verbose_name='Medical record number'),
        ),
    ]
