# Generated by Django 2.2.2 on 2020-03-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacient', '0011_auto_20200229_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='medical_record_number',
            field=models.IntegerField(blank=True, default=16284332, editable=False, null=True, verbose_name='Medical record number'),
        ),
    ]
