# Generated by Django 2.2.2 on 2020-03-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacient', '0012_auto_20200303_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='medical_record_number',
            field=models.IntegerField(blank=True, default=2460992, editable=False, null=True, verbose_name='Medical record number'),
        ),
    ]
