# Generated by Django 2.2.2 on 2020-03-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacient', '0014_auto_20200307_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='medical_record_number',
            field=models.IntegerField(blank=True, default=2925210, editable=False, null=True, verbose_name='Medical record number'),
        ),
    ]
