# Generated by Django 2.2.2 on 2020-03-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacient', '0021_auto_20200314_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='medical_record_number',
            field=models.IntegerField(blank=True, default=18080926, editable=False, null=True, verbose_name='Medical record number'),
        ),
    ]
