# Generated by Django 2.2.2 on 2020-03-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacient', '0022_auto_20200314_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='medical_record_number',
            field=models.IntegerField(blank=True, default=8119766, editable=False, null=True, verbose_name='Medical record number'),
        ),
    ]
