# Generated by Django 2.2.2 on 2020-03-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacient', '0024_auto_20200314_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='medical_record_number',
            field=models.IntegerField(blank=True, default=4940764, editable=False, null=True, verbose_name='Medical record number'),
        ),
    ]
