# Generated by Django 2.2.2 on 2020-03-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacient', '0025_auto_20200321_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='medical_record_number',
            field=models.IntegerField(blank=True, default=18256614, editable=False, null=True, verbose_name='Medical record number'),
        ),
    ]
